# Generated by Django 4.2.5 on 2023-11-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_entrys', '0002_testing'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('event_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Testing',
        ),
    ]
