# Generated by Django 4.2.5 on 2023-10-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_entrys', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image_qr',
            field=models.ImageField(blank=True, null=True, upload_to='entry_qr_codes'),
        ),
    ]
