# Generated by Django 4.2.5 on 2023-11-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_entrys', '0003_scannedvalue_delete_testing'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedvalue',
            name='entry_id',
            field=models.IntegerField(default=16),
            preserve_default=False,
        ),
    ]
