# Generated by Django 4.2.5 on 2023-10-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_entrys', '0003_entry_image_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='event_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
