# Generated by Django 4.2.4 on 2023-09-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_event_start',
            field=models.DateField(),
        ),
    ]
