# Generated by Django 4.2.4 on 2023-09-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_event_date_event_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_event_start',
            field=models.DateTimeField(),
        ),
    ]
