# Generated by Django 4.2.5 on 2023-10-22 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_entry_event_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='event',
            name='creator',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
