# Generated by Django 4.2.5 on 2023-10-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_event_attendees_remove_event_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpromotor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
