# Generated by Django 4.2.5 on 2023-11-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_events', '0002_alter_event_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='punctuation',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
